# lib/schemas/mission.py
# The Mission is the *locked agreement* between user and framework, produced
# by /plan and never mutated afterward. Every downstream artifact (Variant,
# TrialResult, FINAL.md) traces back to a Mission via mission_id.
#
# Mirrors the philosophy from the source repo: "schemas are truth". Free-text
# goals are pinned to enumerable fields so the auditor and curator can reason
# about them programmatically.

from __future__ import annotations
from typing import Literal, Optional
from pydantic import BaseModel, Field, field_validator
import hashlib
import time


# ---------------------------------------------------------------------------
# Capability composition — the 5-tuple analogue of the source repo's
# (temporal_structure, leakage_model, target_type, validation_strategy,
# recommendation_type). For GenAI we compose along axes that actually move
# the design space.
# ---------------------------------------------------------------------------

TaskModality = Literal[
    # What the system is *for*. Each maps to a capability module under
    # lib/capabilities/. Adding a new modality requires both a new
    # capability and an entry in the registry.
    "rag_qa",           # Retrieval-Augmented QA over a corpus
    "nlq_to_query",     # Natural language -> SQL / API call / DSL
    "research_agent",   # Open-ended multi-step research with citations
    "insight_agent",    # Extract structured insights from unstructured docs
    "search_engine",    # Search / recommendation engine ranking with LLM rerank
    "chatbot",          # Multi-turn conversational assistant
]

EvalStrategy = Literal[
    # How we measure success. "judge_llm" uses lib/judges.py with calibration;
    # "exact_match" / "regex" are deterministic; "human_in_loop" suspends the
    # run for a labeling pass.
    "exact_match",
    "regex",
    "judge_llm",
    "embedding_similarity",
    "tool_call_match",   # For NLQ / tool-use missions
    "human_in_loop",
]

RecommendationShape = Literal[
    # What the curator should output at the end.
    "variant_diff",          # "ship this prompt change"
    "config_bundle",         # "ship this whole RAG config"
    "router_policy",         # "use Haiku for X, Sonnet for Y"
    "no_signal",             # honest failure — collect more eval data
]


class SuccessCriterion(BaseModel):
    """One success criterion attached to a Mission.

    Missions can carry multiple criteria (e.g. accuracy AND p95 latency).
    The first criterion whose `is_primary=True` drives termination logic.
    """
    metric: str = Field(..., description="Metric name from lib/eval.py registry, e.g. 'judge_score', 'recall_at_5'.")
    operator: Literal[">=", "<=", ">", "<", "=="] = ">="
    target: float = Field(..., description="The target value the metric must hit.")
    operational_floor: float = Field(..., description="Below this, the mission is considered failed; triggers breakthrough mode.")
    is_primary: bool = False
    # `weight` is used by the curator when computing a composite score for
    # tiebreaks between trials with conflicting metrics.
    weight: float = 1.0


class MissionTuple(BaseModel):
    """The 5-tuple capability composition. Locked at /plan time."""
    task_modality: TaskModality
    eval_strategy: EvalStrategy
    # Latency budget in milliseconds (p95). The auditor rejects any variant
    # whose measured p95 latency exceeds this by >10%.
    latency_budget_ms_p95: Optional[int] = None
    # Cost budget per 1000 user requests in USD. Drives the bandit's
    # cost-aware arm scoring.
    cost_budget_usd_per_1k: Optional[float] = None
    # Safety floor — the *minimum* required pass rate on the red-team suite
    # generated by the Provoker subagent. Below this, the auditor escalates
    # to catastrophic.
    safety_floor: float = 0.95
    recommendation_shape: RecommendationShape = "variant_diff"


class Mission(BaseModel):
    """The user-framework contract. Written once by /plan, read by everything."""
    mission_id: str = Field(..., description="Deterministic hash of the locked fields; used as a foreign key in every artifact.")
    project_name: str
    framework_version: str
    created_at_unix: float = Field(default_factory=time.time)

    # The natural-language goal the user typed. The framework will refer
    # back to this only for prose generation; all decisions are driven by
    # the structured fields below.
    goal_prose: str

    composition: MissionTuple
    success_criteria: list[SuccessCriterion] = Field(..., min_length=1)

    # Domain hint from lib/domains/ — injects priors (e.g. "support_bot"
    # primes the strategist toward refusal/redirect patterns).
    domain: str = "general"

    # The hash of the EvalSet locked at /plan time. Any change to the eval
    # set invalidates this mission (the auditor will refuse to run).
    eval_set_hash: str

    # Total budget for the autonomous /run loop. Each trial's cost is
    # logged to `budget.jsonl` and checked against this ceiling.
    total_budget_usd: float = 50.0
    max_iterations: int = 30
    breakthrough_max_entries: int = 3

    @field_validator("mission_id")
    @classmethod
    def _validate_mission_id_shape(cls, v: str) -> str:
        # Defensive: mission_id should be a 16-char hex prefix; helps catch
        # cases where a caller passed a random string or forgot to compute it.
        if len(v) != 16 or not all(c in "0123456789abcdef" for c in v):
            raise ValueError(f"mission_id must be a 16-char hex string, got: {v!r}")
        return v

    @classmethod
    def compute_id(cls, project_name: str, composition: MissionTuple, eval_set_hash: str, goal_prose: str) -> str:
        """Deterministic mission id. Same inputs -> same id, so re-running
        /plan with identical answers does not orphan prior artifacts."""
        payload = "|".join([
            project_name,
            composition.model_dump_json(),
            eval_set_hash,
            goal_prose.strip(),
        ])
        return hashlib.sha256(payload.encode("utf-8")).hexdigest()[:16]

    def primary_criterion(self) -> SuccessCriterion:
        """Return the criterion that drives termination. If none is marked
        primary, fall back to the first one in declared order."""
        for c in self.success_criteria:
            if c.is_primary:
                return c
        return self.success_criteria[0]
